apps/login_registration/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

apps/wish_list/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'$', views.index, name='index'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^wish_items/create$', views.create, name='create'),
    url(r'^add_item$', views.add_item, name='add_item'),
    url(r'^wish_items/(?P<id>\d+)$', views.display_item, name='display_item'),
    url(r'^add_to_list/(?P<id>\d+)$', views.add_to_list, name='add_to_list'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name='remove'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name='delete')
]

wish_list_main/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.wish_list.urls', namespace='wish_list')),
    url(r'^login_registration/', include('apps.login_registration.urls', namespace='login_registration'))

]

apps/wish_list/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_registration.models import User

class ItemManager(models.Manager):
    def add_item(self, postData, user_id):
        errors = self.validate(postData)
        if not errors:
            added_by = User.objects.get(id=user_id)
            item = Item.objects.create(
                item=postData['item'],
                added_by=added_by
            )
            return item
        else:
            return errors

    def add_to_list(self, item_id, user_id, first_name, last_name):
        wisher = Wisher.objects.create(
            item=Item.objects.get(id=item_id),
            user=User.objects.get(id=user_id),
            first_name=first_name,
            last_name=last_name
        )
        return wisher

    def validate(self, postData):
        errors = []
        if len(postData['item']) == 0:
            errors.append("Item cannot be blank!")
        if len(postData['item']) < 4:
            errors.append("Item name must be more than 3 characters!")
        return errors

class Item(models.Model):
    item = models.CharField(max_length=255)
    added_by = models.ForeignKey(User, related_name='user')
    wishers = models.ManyToManyField(User, through='Wisher')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ItemManager()

    def __str__(self):
        return self.item

class Wisher(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    item = models.ForeignKey(Item)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

apps/wish_list/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Item, Wisher
from ..login_registration.models import User
import types

def index(request):
    return render(request, 'login_registration/index.html')

def dashboard(request):
    try:
        items = Item.objects.filter(added_by=request.session['user_id']) | \
            Item.objects.filter(users=request.session['user_id'])
        other_items = Item.objects.all().exclude(added_by=request.session['user_id'])
    except Item.DoesNotExist:
        items = None
        other_items = None
    context = {
        'items': items,
        'other_items': other_items
    }
    return render(request, 'wish_list/dashboard.html', context)

def create(request):
    return render(request, 'wish_list/create.html')

def add_item(request):
    if request.method != 'POST':
        return redirect(reverse('wish_list:create'))
    else:
        item = Item.objects.add_item(request.POST, request.session['user_id'])
        if isinstance(item, types.ListType):
            for error in item:
                messages.error(request, error)
            return redirect(reverse('wish_list:create'))
        else:
            messages.success(request, "Successfully added an item to your wish list!")
            return redirect(reverse('wish_list:dashboard'))

def display_item(request, id):
    item = Item.objects.get(id=id)
    added_by = User.objects.get(id=request.session['user_id'])
    context = {
        'item': item,
        'wishers': Wisher.objects.filter(item=item).exclude(user=added_by)
    }
    return render(request, 'wish_list/display.html', context)

def add_to_list(request, id):
    Item.objects.add_to_list(id, request.session['user_id'], request.session['first_name'], request.session['last_name'])
    messages.success(request, "Successfully added item to Wish List!")
    return redirect(reverse('wish_list:dashboard'))

def remove(request, id):
    Wisher.objects.filter(user=request.session['user_id']).get(item=id).delete()
    messages.success(request, "Successfully removed item from your Wish List!")
    return redirect(reverse('wish_list:dashboard'))

def delete(request, id):
    Item.objects.get(id=id).delete()
    messages.success(request, "Successfully deleted item!")
    return redirect(reverse('wish_list:dashboard'))

apps/wish_list/templates/wish_list/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Item</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'wish_list/css/style.css' %}">
  </head>
  <body>
    <div class="navbar">
      <h3>Create a new Wish List Item</h3>
      <a href="{% url 'wish_list:dashboard' %}">Home</a>
      <a href="{% url 'login_registration:logout' %}">Log Out</a>
    </div>
    <div class="container">
      <form action="{% url 'wish_list:add_item' %}" method="post">
        {% csrf_token %}
        <label>Item/Product:</label><input type="text" name="item">
        <input type="submit" value="Add">
      </form>
    </div>
    <div class="errors">
      {% if messages %}
        {% for message in messages %}
          <p>{{message}}</p>
        {% endfor %}
      {% endif %}
    </div>
  </body>
</html>

apps/wish_list/templates/wish_list/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My Wish List</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'wish_list/css/style.css' %}">
  </head>
  <body>
    <div class="navbar">
      <h3>Hello, {{request.session.first_name}}!</h3>
      <a href="{% url 'login_registration:logout' %}">Log Out</a>
    </div>
    <div class="container">
      <div class="my_wish_list">
        <h4>My Wish List</h4>
        <table>
          <thead>
            <tr>
              <th>Item</th>
              <th>Added By</th>
              <th>Date Added</th>
              <th>Action</th>
            </tr>
          </thead>
          {% if items %}
            <tbody>
              {% for item in items %}
                <tr>
                  <td><a href="{% url 'wish_list:display_item' id=item.id %}">{{item.item}}</a></td>
                  <td>{{item.added_by}}</td>
                  <td>{{item.created_at}}</td>
                  <td>
                    {% if item.added_by.id == request.session.user_id %}
                      <a href="{% url 'wish_list:delete' id=item.id %}">Delete</a>
                    {% else %}
                      <a href="{% url 'wish_list:remove' id=item.id %}">Remove from Wish List</a>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          {% endif %}
        </table>
      </div>
      <div class="other_wish_list">
        <h4>Other Users' Wish List</h4>
        <table>
          <thead>
            <tr>
              <th>Item</th>
              <th>Added By</th>
              <th>Date Added</th>
              <th>Action</th>
            </tr>
          </thead>
          {% if other_items %}
            <tbody>
              {% for other_item in other_items %}
                <tr>
                  <td><a href="{% url 'wish_list:display_item' id=other_item.id %}">{{other_item.item}}</a></td>
                  <td>{{other_item.added_by}}</td>
                  <td>{{other_item.created_at}}</td>
                  <td>
                    <a href="{% url 'wish_list:add_to_list' id=other_item.id %}">Add to my Wish List</a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          {% endif %}
        </table>
      </div>
      <a href="{% url 'wish_list:create' %}">Add Item</a>
      <div class="errors">
        {% if messages %}
          {% for message in messages %}
            <p>{{message}}</p>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </body>
</html>

apps/wish_list/templates/wish_list/display.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{item.item}}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'wish_list/css/style.css' %}">
  </head>
  <body>
    <div class="navbar">
      <h3>{{item.item}}</h3>
      <a href="{% url 'wish_list:dashboard' %}">Home</a>
      <a href="{% url 'login_registration:logout' %}">Log Out</a>
    </div>
    <div class="container">
      <p>Users who added this item to their Wish List:</p>
      {% if wishers %}
        <ul>
          {% for wisher in wishers %}
            <li>{{wisher.first_name}} {{wisher.last_name}}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>
    <div class="errors">
      {% if messages %}
        {% for message in messages %}
          <p>{{message}}</p>
        {% endfor %}
      {% endif %}
    </div>
  </body>
</html>