apps/login_registration/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

wish_list_main/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.wish_list.urls', namespace='wish_list')),
    url(r'^login_registration/', include('apps.login_registration.urls', namespace='login_registration'))

]

apps/login_registration/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
import re

# regex to test whether given name contains letters only and is no fewer than 2 characters
name_regex = re.compile(r'[A-Za-z]{3,}')
# regex to test whether given username contains at least 3 characters
username_regex = re.compile(r'[A-Za-z0-9]{3,}')
# regex to test whether given password is at least 8 characters long
password_regex = re.compile(r'(?=.{8,})')

class UserManager(models.Manager):
    def register(self, postData):
        # runs validation test
        errors = self.validate(postData)
        # creates a hashed password
        # and stores user information into a new User object
        if not errors:
            hashed_password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
            user = User.objects.create(
                first_name=postData['first_name'],
                last_name=postData['last_name'],
                username=postData['username'],
                password=hashed_password
            )
            return user
        else:
            return errors

    # searches for Users matching the given email and tests whether the given
    # password matches the stored password
    def login(self, postData):
        user = User.objects.filter(username=postData['username'])
        if not user:
            return False
        if bcrypt.hashpw(postData['password'].encode(), user[0].password.encode()) != user[0].password.encode():
            return False
        else:
            return user[0]

    # deletes the session attached to the given user id
    def logout(self, session):
        del session
        return True

    # tests whether given user first name, last name, email, and password
    # are all valid
    def validate(self, postData):
        errors = []
        try:
            user = User.objects.get(username=postData['username'])
            errors.append("Username already exists! Please log in!")
        except:
            if not re.match(name_regex, postData['first_name']):
                errors.append("First name must be more than 3 characters!")
            if not re.match(name_regex, postData['last_name']):
                errors.append("Last name must be more than 3 characters!")
            if not re.match(username_regex, postData['username']):
                errors.append("Username must be more than 3 characters!")
            if not re.match(password_regex, postData['password']):
                errors.append("Password is invalid!")
            elif postData['password'] != postData['confirm_password']:
                errors.append("Passwords do not match!")
        return errors

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

apps/login_registration/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User
import types

# displays a page where user can either register or log in
def index(request):
    return render(request, 'login_registration/index.html')

# registers user name, email, and password if all information is valid
def register(request):
    if request.method != 'POST':
        return redirect(reverse('login_registration:index'))
    else:
        user = User.objects.register(request.POST)
        if isinstance(user, types.ListType):
            for error in user:
                messages.error(request, error)
            return redirect(reverse('login_registration:index'))
        else:
            request.session['user_id'] = user.id
            request.session['first_name'] = user.first_name
            request.session['last_name'] = user.last_name
            messages.success(request, "Successfully registered!")
            print "Here!"
            return redirect(reverse('wish_list:dashboard'))

# logs in user if user information is valid and saves information into a session
def login(request):
    if request.method != 'POST':
        return redirect(reverse('login_registration:index'))
    else:
        user = User.objects.login(request.POST)
        if not user:
            messages.error(request, "Invalid Username or Password!")
            return redirect(reverse('login_registration:index'))
        else:
            request.session['user_id'] = user.id
            request.session['first_name'] = user.first_name
            request.session['last_name'] = user.last_name
            messages.success(request, "Successfully logged in!")
            return redirect(reverse('wish_list:dashboard'))

# logs out a user and deletes session containing user information
def logout(request):
    User.objects.logout(request.session['user_id'])
    messages.success(request, "Successfully logged out!")
    return redirect(reverse('login_registration:index'))

apps/login_registration/templates/login_registration/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Registration Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'login_registration/css/style.css' %}">
  </head>
  <body>
    <div class="page_top">
      <h3>Login and Registration App</h3>
    </div>
    <div class="wrapper">
      <div class="register">
        <h2>Register</h2>
        <form action="{% url 'login_registration:register' %}" method="post">
          {% csrf_token %}
          <label>First Name: </label><input type="text" name="first_name">
          <label>Last Name: </label><input type="text" name="last_name">
          <label>Username: </label><input type="text" name="username">
          <label>Password: </label><input type="text" name="password">
          <label>Confirm Password: </label><input type="text" name="confirm_password">
          <input type="submit" value="Register">
        </form>
      </div>
      <div class="login">
        <h2>Log In</h2>
        <form action="{% url 'login_registration:login' %}" method="post">
          {% csrf_token %}
          <label>Username: </label><input type="text" name="username">
          <label>Password: </label><input type="text" name="password">
          <input type="submit" value="Log In">
        </form>
      </div>
      <div class="errors">
        {% if messages %}
          {% for message in messages %}
            <p>{{message}}</p>
          {% endfor %}
        {% endif %}
      </div>
    </div>
  </body>
</html>